const DICT = {
  es: {
    nav_carta: "Carta",
    nav_concepto: "Concepto",
    nav_reservar: "Reservar",
    btn_menu: "Menú",
    btn_reservar: "Reservar Mesa",
    hero_desc: "Cocina de verdad, hecha con las manos y a fuego lento. Recetas de toda la vida, producto de mercado y mucho mimo en cada plato. Aquí vienes a disfrutar.",
    marquee: "Gastrobar Premium • Producto de Mercado • Recetas de Siempre • Gastrobar Premium • Producto de Mercado • Recetas de Siempre • ",
    concept_title: "Nuestra<br>esencia",
    concept_desc: "Nos gusta el bar de siempre, pero bien hecho. Creemos en los guisos, en el producto fresco y en cuidar cada detalle para que te sientas como en casa.",
    concept_badge: "Tradición / 01",
    gallery_img0: "Tiras de Pollo<br>Rebozadas",
    gallery_img1: "Burrata<br>Secchiello",
    gallery_img2: "Alcachofas<br>Tudela",
    gallery_img3: "Carrillera<br>Vino Tinto",
    carta_title: "La Carta",
    footer_hours: "Lun - Dom / 08:00 - 01:00",
    footer_rights: "© 2026 Todos los derechos reservados.",
    close_btn: "Cerrar [X]"
  },
  en: {
    nav_carta: "Menu",
    nav_concepto: "Concept",
    nav_reservar: "Book",
    btn_menu: "Menu",
    btn_reservar: "Book a Table",
    hero_desc: "Real food, made by hand and slow-cooked. Lifelong recipes, fresh market produce, and care in every dish. You come here to enjoy.",
    marquee: "Premium Gastrobar • Market Produce • Classic Recipes • Premium Gastrobar • Market Produce • Classic Recipes • ",
    concept_title: "Our<br>essence",
    concept_desc: "We love the classic local bar, but done right. We believe in slow stews, fresh ingredients, and taking care of every detail so you feel at home.",
    concept_badge: "Tradition / 01",
    gallery_img0: "Breaded<br>Chicken Strips",
    gallery_img1: "Secchiello<br>Burrata",
    gallery_img2: "Tudela<br>Artichokes",
    gallery_img3: "Red Wine<br>Pork Cheek",
    carta_title: "The Menu",
    footer_hours: "Mon - Sun / 08:00 - 01:00",
    footer_rights: "© 2026 All rights reserved.",
    close_btn: "Close [X]"
  },
  ca: {
    nav_carta: "Carta",
    nav_concepto: "Concepte",
    nav_reservar: "Reservar",
    btn_menu: "Menú",
    btn_reservar: "Reservar Taula",
    hero_desc: "Cuina de veritat, feta amb les mans i a foc lent. Receptes de tota la vida, producte de mercat i molt de mim en cada plat. Aquí vens a gaudir.",
    marquee: "Gastrobar Premium • Producte de Mercat • Receptes de Sempre • Gastrobar Premium • Producte de Mercat • Receptes de Sempre • ",
    concept_title: "La nostra<br>essència",
    concept_desc: "Ens agrada el bar de sempre, però ben fet. Creiem en els guisats, en el producte fresc i en cuidar cada detall perquè et sentis com a casa.",
    concept_badge: "Tradició / 01",
    gallery_img0: "Tires de Pollastre<br>Arrebossat",
    gallery_img1: "Burrata<br>Secchiello",
    gallery_img2: "Carxofes<br>Tudela",
    gallery_img3: "Galta al<br>Vi Negre",
    carta_title: "La Carta",
    footer_hours: "Dll - Dmg / 08:00 - 01:00",
    footer_rights: "© 2026 Tots els drets reservats.",
    close_btn: "Tancar [X]"
  }
};
